# 提示文档列表
message:
  # 通用类型
  common:
    # 交互限制, 限制某些方块必须创造模式下才允许交互
    interact_limit:
      left_click:
        - "PIXELMON_POKE_CHEST"
        - "PIXELMON_ULTRA_CHEST"
        - "PIXELMON_BEAST_CHEST"
        - "PIXELMON_MASTER_CHEST"
      right_click: [ ]
      notify: "&c系统提示 &f你不能这样子做."
  # 宝可梦相关提示+
  pixelmon:
    # 克隆机
    clone:
      # 是否开启
      enable: true
      broken: "&c系统 &e损坏!"
      normal: "&c系统 &e正常的克隆机!"
      error: "&c系统 &e请右键克隆机左下角!"
    # 果树催熟
    apricorn:
      #是否开启
      enable: true
      # 是否直接掉落
      break: true
      # 请填入方块名, 如果是任何方块都不允许请填写 all
      check:
        - "WHITE_SHULKER_BOX"
        - "ORANGE_SHULKER_BOX"
        - "MAGENTA_SHULKER_BOX"
        - "LIGHT_BLUE_SHULKER_BOX"
        - "YELLOW_SHULKER_BOX"
        - "LIME_SHULKER_BOX"
        - "PINK_SHULKER_BOX"
        - "GRAY_SHULKER_BOX"
        - "SILVER_SHULKER_BOX"
        - "CYAN_SHULKER_BOX"
        - "PURPLE_SHULKER_BOX"
        - "BLUE_SHULKER_BOX"
        - "BROWN_SHULKER_BOX"
        - "GREEN_SHULKER_BOX"
        - "RED_SHULKER_BOX"
        - "BLACK_SHULKER_BOX"
        - "CHEST"
      deny: "&c系统提示 &f请将果树上的潜影盒拆下来再进行操作!"
    # 进化卸下物品
    evolving:
      deny: "&c系统提示 &f进化过程中, 无法使用该道具."
    # 精灵 UUID 相同
    repeat-uuid:
      # 是否开启该模块
      enable: true
      # 检测间隔, 单位: 秒, 修改后需重启生效
      delay: 60
      deny: "&c系统提示 &f背包中出现重复UUID精灵, 已移除其中一只."
    # 技能复制携带物品
    skill-copy-item:
      # 是否开启该模块
      enable: true
    # 幽灵系精灵不掉落物品
    ghost_drop:
      # 是否开启该模块, 高于 8.2.0 不会启用, 因为 8.2.0 已修复此问题
      enable: true
    # 剑盾切换形态属性及种族值不变
    form_stats:
      # 是否开启该模块, 如果未来 PixelmonReforged 模组修复了该问题, 请关闭本模块
      # 本模块改动需重启服务器来重置模块
      enable: true
    # 捕捉连击
    combo:
      # 是否开启该模块
      enable: true
    # 修复卡进化, 等级达标但是没进化
    evolution:
      # 是否开启该模块
      enable: true
    # 是否禁止精灵能进入载具
    vehicle:
      # 是否开启该模块
      enable: true
  # 潘马斯模组
  pams:
    machinery:
      # 是否开启该模块
      enable: true
      # 检测的方块列表, 下面只放入一个例子, 请填写方块名
      check:
        - "HARVESTCRAFT_WATERFILTER"
      deny: "&c系统提示 &f有人正在查看界面喔, 无法破坏该方块!"
  # WorldGuard
  worldguard:
    # 无视权限放置
    place:
      enable: true
      deny: "&c系统提示 &f请使用主手来放置方块或只有一只手拿着物品!"
  # Sakura 催熟刷物品
  sakura:
    # 催熟刷物品
    grow:
      enable: true
      # 检测的对象列表
      list:
        - "SAKURA_BAMBOO_SHOOT"
        - "SAKURA_BAMBOO"
      # 是否直接掉落
      break: true
      # 校对的容器列表
      check:
        - "WHITE_SHULKER_BOX"
        - "ORANGE_SHULKER_BOX"
        - "MAGENTA_SHULKER_BOX"
        - "LIGHT_BLUE_SHULKER_BOX"
        - "YELLOW_SHULKER_BOX"
        - "LIME_SHULKER_BOX"
        - "PINK_SHULKER_BOX"
        - "GRAY_SHULKER_BOX"
        - "SILVER_SHULKER_BOX"
        - "CYAN_SHULKER_BOX"
        - "PURPLE_SHULKER_BOX"
        - "BLUE_SHULKER_BOX"
        - "BROWN_SHULKER_BOX"
        - "GREEN_SHULKER_BOX"
        - "RED_SHULKER_BOX"
        - "BLACK_SHULKER_BOX"
        - "CHEST"
      deny: "&c系统提示 &f请将催熟对象上的方块拆下来再进行操作!"
  # 时装模组
  armourers:
    # 无视权限无限放置时装方块
    place:
      # 是否开启该模块
      enable: true