name: Fixer
main: com.blank038.fixer.Fixer
version: ${version}
depend:
  - PokemonAPI
softdepend:
  - WorldGuard
  - Slimefun
  - ProtocolLib
  - PacketListenerApi
commands:
  fixer:
    description: Command for Fixer.