name: Fixer
main: com.blank038.fixer.bukkit.Fixer
version: ${version}
load: STARTUP
depend:
  - PokemonAPI
softdepend:
  - WorldGuard
  - Slimefun
  - ProtocolLib
  - PacketListenerApi
commands:
  fixer:
    description: Command for Fixer.